name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout TrustyAI explainability repo
        uses: actions/checkout@v2
        with:
          repository: 'trustyai-explainability/trustyai-explainability'
          path: 'trustyai-explainability'

      - name: Build TrustyAI explainability with Maven
        run: |
          cd trustyai-explainability
          mvn clean install -DskipTests

      - name: Build and test with Maven
        run: mvn clean test
